christinee.liu
samnjab/Quotify pull request #5
Opened 2024-11-22 02:23 UTC by chrisliux

2024-11-22 21:56 UTC, samnjab commented on .idea/compiler.xml
Make sure .idea is added to .gitignore file so moving forward, the xml files in this folder won't be altered.

2024-11-22 21:58 UTC, samnjab commented on .idea/misc.xml
Same issue here, the JDK builds are different across branches, make sure you exclude build level files from commits.

2024-11-23 03:01 UTC, samnjab requested changes

2024-11-23 03:01 UTC, samnjab commented on src/main/java/quotify_app/adapters/comparator/ComparatorState.java
> +    public void setList1(ArrayList<Object> list1) {
The use of Object as the specified type in method arguments is overly general. It can lead to type-casting issues. Use <Property> instead to make sure type issues are detected at compile time.
Using ArrayList<> in the method signatures restricts flexibility. A user might have a LinkedList or another List implementation they'd like to pass in. Use the List<> interface in both the class fields and method parameters.

2024-11-23 03:01 UTC, samnjab commented on src/main/java/quotify_app/adapters/comparator/ComparatorState.java
> +    private ArrayList<Object> list1;
Use List<Property> for class fields for more flexibility in client code of this class, as well as better readability of the type of objects these fields are supposed to hold.

2024-11-23 03:01 UTC, samnjab commented on src/main/java/quotify_app/adapters/comparator/ComparatorState.java
> +    private ArrayList<Object> list1;
I don't know why parts of my comments get deleted. Use `List<Property>` is what I meant to say

2024-11-23 03:01 UTC, samnjab commented on src/main/java/quotify_app/adapters/comparator/ComparatorState.java
> +    public void setList1(ArrayList<Object> list1) {
Use `List<Property>` instead.

2024-11-23 03:01 UTC, samnjab commented on src/main/java/quotify_app/adapters/comparator/ComparatorState.java
> +    private ArrayList<Object> list2;
It is not clear what list1, list2, and list3 are representing. Be more descriptive with the field names.

2024-11-23 03:01 UTC, samnjab commented on src/main/java/quotify_app/adapters/comparator/ComparatorViewModel.java
> +    public static final String HOUSE1_LABEL = "House 1";
Choosing to restrict the number of properties presented in the ViewModel is interesting.  We could discuss whether the decision of how many Properties are presented in the View should be made by the Interactor or the View. 
So question is: are the "similar properties" to be presented better kept in an array, in which case you only need one label for the whole group of them say "Similar Properties", instead of 3 separate labels House 1, House 2, House 3, which could very well be subject to change depending on whether we choose to present more similar properties.

2024-11-23 03:01 UTC, samnjab commented on src/main/java/quotify_app/adapters/comparator/ComparatorViewModel.java
> +    public static final String HOUSE1_LABEL = "House 1";
One minor note is not all Properties are Houses, some are condos etc.

2024-11-23 03:01 UTC, samnjab commented on src/main/java/quotify_app/adapters/function/FunctionViewModel.java
> +    public static final String COMPARE_LABEL = "Compare with similar property";
Minor spelling note in the labels:
Estimate Price
Compare Similar Properties

2024-11-23 03:32 UTC, chrisliux commented on src/main/java/quotify_app/adapters/comparator/ComparatorViewModel.java
> +    public static final String HOUSE1_LABEL = "House 1";
I tried modify not to restrict the number of properties presented in the ViewModel by storing each property list be stored an ArrayList (which can be dynamically adjusts its capacity when elements are added or removed).

2024-11-23 03:36 UTC, chrisliux commented on src/main/java/quotify_app/adapters/comparator/ComparatorState.java
> +    private ArrayList<Object> list2;
Identified the private attribute **List<List<Object>> lists** in javadoc

2024-11-23 05:06 UTC, chrisliux commented on src/main/java/quotify_app/adapters/comparator/ComparatorState.java
> +    public void setList1(ArrayList<Object> list1) {
You're right. I created a new Property class in entities folder to holds the data for each property.

2024-11-23 05:09 UTC, chrisliux commented on src/main/java/quotify_app/adapters/comparator/ComparatorViewModel.java
> +    public static final String HOUSE1_LABEL = "House 1";
Nice catch! I changed all the 'house' to 'property' across my code.

2024-11-23 17:39 UTC, samnjab approved these changes
Awesome! I'm approving the new Property entity to prevent crashing for now , but keep in mind this is going to be replaced by a more comprehensive entity.

2024-11-23 17:39 UTC, merged